name: Provision EC2 Instances with terraform

on:
  push:
    branches:
      - main

jobs:
  terraform-provision:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Plan Terraform Changes
      - name: Terraform Plan
        run: terraform plan

      # Step 5: Apply Terraform Configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve
